name: Build Daken Radar
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.11
          subcommand: android debug
          # هذا السطر يخبره أن يبحث في الصفحة الرئيسية
          workdir: . 

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Daken-Radar-APK
          path: bin/*.apk
